In [96]:
import numpy as np

In [147]:
import pandas as pd
import numpy as np
wr1 = pd.read_csv('wr2.csv',encoding='ISO-8859-1')

#df = pd.DataFrame()
wr2=wr1

In [2]:
wr2 = wr2[((wr2.VALUE.isnull()) | (wr2.VALUE == 'Unclear') | (wr2.VALUE == 'Unknown'))]
company_list = wr2['COMPANY NAME'].unique()
random_company = np.random.choice(company_list,5)
wr2 = wr2[wr2['COMPANY NAME'].isin(random_company)]

In [3]:
random_company

array(['John Keells Holdings PLC', 'Sodexo', 'American Express',
       'Harvey Nichols Group', 'Energy Australia'], dtype=object)

In [4]:
def splitt(ss):
    return ss.split('+')[-1]

In [5]:
wr2['METRIC NAME']=wr2['METRIC NAME'].apply(splitt)

In [6]:
wr2

,METRIC NAME,COMPANY NAME,YEAR,VALUE
33816,MSA supply chain disclosure,Harvey Nichols Group,2016,Unknown
33817,MSA risk management (revised),Harvey Nichols Group,2016,Unknown
33824,MSA Performance Indicators,Harvey Nichols Group,2017,Unknown
33825,MSA Business Performance Indicators,Harvey Nichols Group,2016,Unknown
33826,Laureen van Breen,Harvey Nichols Group,2016,Unknown
92314,Environmental fines (G4-EN29-a),Energy Australia,2014,Unknown
92316,Collective bargaining (G4-11),Energy Australia,2014,Unknown
92317,Water Recycled (%) (G4-EN10-b),Energy Australia,2014,Unknown
92318,Reduction in energy requirements of products a...,Energy Australia,2014,Unknown
92319,Recycled Input Materials (G4-EN2-a),Energy Australia,2014,Unknown
92321,NOx emissions (G4-EN21-a),Energy Australia,2014,Unknown
92322,Volatile Organic Compounds (VOC) emissions (G4...,Energy Australia,2014,Unknown
92331,Municipal water withdrawals (G4-EN8-a),Energy Australia,2014,Unknown
92332,Rainwater collected directly and stored (G4-EN...,Energy Australia,2014,Unknown
92334,Highest paid worker to median worker pay ratio...,Energy Australia,2014,Unknown
92335,Local suppliers spending (G4-EC9-a),Energy Australia,2014,Unknown
92337,Health and Safety representation (G4-LA5-b),Energy Australia,2014,Unknown
92338,Ground Water Withdrawals (G4-EN8-a),Energy Australia,2014,Unknown
92339,Gender Entry Level Pay (G4-EC5),Energy Australia,2014,Unknown
92340,Senior management hired from local community (...,Energy Australia,2014,Unknown
92341,Waste Water Used (G4-EN8-a),Energy Australia,2014,Unknown
92346,Total water withdrawals (G4-EN8-a),Energy Australia,2014,Unknown
92351,Water Use,Energy Australia,2014,Unknown
155255,Indirect legacy (G4-EO13-b),American Express,2016,Unknown
155264,Greenhouse gas (GHG) emissions intensity ratio...,American Express,2016,Unknown
155280,Accessibility initiatives (G4-EO6-a),American Express,2016,Unknown
155281,Socially inclusive initiatives (G4-EO5-a),American Express,2016,Unknown
155287,Worker fatalities (G4-LA6-a),American Express,2016,Unknown
155288,Collective bargaining (G4-11),American Express,2016,Unknown
226580,Non-Hazardous Waste Recycled (G4-EN23-a),John Keells Holdings PLC,2015,Unknown
...,...,...,...,...
250039,Fuel consumption from non-renewable sources (G...,Sodexo,2016,Unknown
250040,Percentage renewable fuel used,Sodexo,2016,Unknown
250041,Renewable Energy (%),Sodexo,2016,Unknown
250042,energy is from renewable sources,Sodexo,2016,Unknown
250043,Energy Consumption Outside the Organization (G...,Sodexo,2016,Unknown
250044,Indirect greenhouse gas (GHG) emissions (Scope...,Sodexo,2016,Unknown
250045,Greenhouse Gas Emissions Scope 2,Sodexo,2016,Unknown
250046,Direct greenhouse gas (GHG) emissions (Scope 1...,Sodexo,2016,Unknown
250047,Greenhouse Gas Emissions Scope 1,Sodexo,2016,Unknown
250048,Greenhouse Gas Emissions Scope 1 and 2 combined,Sodexo,2016,Unknown
250049,Progress Scope 1 Emissions,Sodexo,2016,Unknown
250050,Combined Scope 1 and 2 Greenhouse Gas emissions,Sodexo,2016,Unknown
250051,Worker fatalities (G4-LA6-a),Sodexo,2016,Unknown
250052,Male worker fatalities (G4-LA6-a),Sodexo,2016,Unknown
250053,Female worker fatalities (G4-LA6-a),Sodexo,2016,Unknown
250054,Occupational Risk (G4-LA7),Sodexo,2016,Unknown
250055,Total Waste Generated (G4-EN23-a),Sodexo,2016,Unknown
250056,Total Waste to Landfill (G4-EN23-a),Sodexo,2016,Unknown
250057,Hazardous Waste Created (G4-EN23-a),Sodexo,2016,Unknown
250058,Non-hazardous waste (G4-EN23-a),Sodexo,2016,Unknown
250059,Total Waste Recycled (G4-EN23-a),Sodexo,2016,Unknown
250060,Percentage of waste recycled,Sodexo,2016,Unknown
250061,Hazardous waste recycled (G4-EN23-a),Sodexo,2016,Unknown
250062,Percentage hazardous waste recycled,Sodexo,2016,Unknown
250063,Non-Hazardous Waste Recycled (G4-EN23-a),Sodexo,2016,Unknown
250064,Percentage non-hazardous waste recycled,Sodexo,2016,Unknown
250065,Access to Healthcare for Work-related Incidents,Sodexo,2016,Unknown
250072,Sulfur Oxide (SOx) emissions (G4-EN21-a),Sodexo,2017,Unknown
250073,Total water discharge (G4-EN22-a),Sodexo,2017,Unknown
250074,Volatile Organic Compounds (VOC) emissions (G4...,Sodexo,2017,Unknown

In [7]:
%ls

 Volume in drive C is Windows
 Volume Serial Number is 0CF9-4541

 Directory of C:\Users\yzhhu\Desktop\stanley_svymky

2019/07/31  17:55    <DIR>          .
2019/07/31  17:55    <DIR>          ..
2019/07/31  17:29    <DIR>          .ipynb_checkpoints
2019/07/31  14:44    <DIR>          __pycache__
2019/07/30  16:11           134,020 crwdsurveymky_English_uie.ipynb
2019/07/12  15:37            34,994 crwdsurveymky_Spanish_uie.ipynb
2019/07/30  15:01            65,933 data prepare .ipynb
2019/07/31  17:55            57,788 dummy_data.ipynb
2019/07/30  10:25            14,717 GCI Units and Value Ranges - June03 - REVISED.xlsx
2019/07/30  16:08            15,769 process_functions.py
2019/07/12  15:37             2,733 README.md
2019/07/31  17:27            15,558 stanley_newmky.ipynb
2019/07/31  15:25               856 table.csv
2019/07/31  15:34               393 test3.py
2019/07/29  19:46    <DIR>          wr2
2019/07/11  13:50        26,239,411 wr2.csv
2019/07/12  15:37         2,813,812 wr2.zip
              12 File(s)     29,395,984 bytes
               5 Dir(s)  353,369,010,176 bytes free

In [8]:
target=pd.read_excel('GCI Units and Value Ranges - June03 - REVISED.xlsx')

In [13]:
target.dropna(subset=['Indicators'],inplace=True)

In [14]:
def spl (ss):
    return ss.split('.')[-1]

In [17]:
def spl2 (ss):
    return ss.split('')

In [15]:
target['Indicators']=target['Indicators'].apply(spl)

In [16]:
target

,Index,Area,Indicators,Measurement,Units,Valid Range
1,A.1.,Revenue and/or (net) value added,Revenue,IFRS 15,Option to express in USD or Euros for consistency,"[0, 1,000,000,000,000]"
2,NaN,NaN,Value added,"Revenue minus costs of bought-in materials, go...",Option to express in USD or Euros for consistency,"[-1,000,000,000,000, 1,000,000,000,000]"
3,NaN,NaN,Net value added,"Revenue minus costs of bought-in materials, go...",Option to express in USD or Euros for consistency,"[-1,000,000,000,000, 1,000,000,000,000]"
4,A.2.,Payments to the Government,Taxes and other payments to the Government,Total amount of taxes paid and payable (encomp...,Option to express in USD or Euros for consistency,"[0, 10,000,000,000]"
5,A.3.,New investment/expenditures,1 Green investment,Total amount of expenditures for those invest...,Option to express in USD or Euros for consiste...,"[0, 1,000,000,000,000] / [0,1]"
6,NaN,NaN,Community investment,Total amount of charitable/voluntary donations...,Option to express in USD or Euros for consiste...,"[0, 1,000,000,000,000] / [0,1]"
7,NaN,NaN,Total expenditures on research and development,Total amount of expenditures on research and d...,Option to express in USD or Euros for consiste...,"[0, 1,000,000,000,000] / [0,1]"
8,A.4.,Local supplier/purchasing programmes,Percentage of local procurement,Proportion of procurement spending of a report...,"$, € / %","[0, 1,000,000,000,000] / [0,1]"
11,B.1.,Sustainable use of water,Water recycling and reuse,Total volume of water recycled and/or reused b...,cubic meters / %,"[0, 1,000,000,000] / [0,1]"
12,NaN,NaN,Water use efficiency,Water use per net value added in the reporting...,"cubic meters per $, € of Net Value Added / %","[0, 1,000,000,000] / [0,1]"
13,NaN,NaN,Water stress,Water withdrawn with a breakdown by sources (s...,cubic meters / %,"[0, 1,000,000,000] / [0,1]"
14,B.2.,Waste management,Reduction of waste generation,Change in the entity’s waste generation per ne...,"cubic meters per $, € of Net Value Added / %","[0, 1,000,000,000,000] / [0,1]"
15,NaN,NaN,"Waste reused, re-manufactured and recycled","Total amount of waste reused, re-manufactured ...",cubic meters / % / Change,"[0, 1,000,000,000,000] / [0,1] / [-1,+1]"
16,NaN,NaN,Hazardous waste,"Total amount of hazardous waste, in absolute t...",kilos and tons / % / Change,"[0, 1,000,000,000,000] / [0,1] / [-1,+1]"
17,B.3.,Greenhouse gas emissions,Greenhouse gas emissions (scope 1),"Scope 1 contribution in absolute amount, in % ...",tons / % / Change,"[0, 1,000,000,000,000] / [0,1] / [-1,+1]"
18,NaN,NaN,Greenhouse gas emissions (scopes 2),"Scope 2 contribution in absolute amount, in % ...",tons / % / Change,"[0, 1,000,000,000,000] / [0,1] / [-1,+1]"
19,B.4.,Ozone-depleting substances and chemicals,Ozone-depleting substances and chemicals,Total amount of ozone-depleting substances (OD...,"kilogrammes per €, $ etc","[0, 1,000,000,000,000)"
21,B.5.,Energy consumption,Renewable energy,Renewable energy consumption as percentage of ...,%,"[0,1]"
22,NaN,NaN,Energy efficiency,Energy consumption per net value added,"joules per €, $ of Net Value Added","[0, 1,000,000,000,000)"
24,C.1.,Gender equality,Proportion of women in managerial positions,Number of women in managerial positions to tot...,integers,"[0, 1,000,000)"
25,C.2.,Human capital,Average hours of training per year per employee,Average number of hours of training per employ...,Hours per Year / Hours per Employee Category,"[0,8760]"
26,NaN,NaN,Expenditure on employee training per year per...,Direct and indirect costs of training (includi...,"$, € per Employee per Year / By Category","[0, 1,000,000,000,000] / [0, 1,000,000,000,..."
27,NaN,NaN,Employee wages and benefits as a proportion o...,Total costs of employee workforce (wages and b...,"$, €","[0, 1,000,000,000,000,000]"
28,C.3.,Employee health and safety,Expenditures on employee health and safety as...,Total expenses for occupational safety and hea...,"$, €; %","[0, 10,000,000,000,000]"
29,NaN,NaN,Frequency/incident rates of occupational inju...,Frequency rates: number of new injury cases di...,"Integers / Hours, %","[0, 1,000,000,000) / [0, 1,000,000]"
30,C.4.,Coverage by collective agreements,Percentage of employees covered by collective...,Number of employees covered by collective agre...,Integers; %,"[0, 1,000,000,000,000]"
31,D,Institutional area,,NaN,NaN,NaN
32,D.1.,Corporate Governance Disclosures,Number of board meetings and attendance rate,Number of board meetings during the reporting ...,Integers / Numerical Value,Integers / Numerical Value
33,NaN,NaN,Number and percentage of female board members,Female board members to total board members,Numerical Value / %,"[0, 1,000,000,000,000] / [0,1]"
34,NaN,NaN,Board members by age range,"Number of Board members by age range (e.g., un...",Intergers per Age Range,"[0, 1,000]"
35,NaN,NaN,Number of meetings of audit committee and att...,Number of board meetings during the reporting ...,Integers / Numerical Value,Integers / Numerical Value
36,NaN,NaN,Compensation: total compensation per board me...,Total annual compensation (including base sala...,"$, € per Executive Director / $, € per Non-Ex...","[0, 1,000,000,000,000]"
37,D.2.,Anti-corruption practices,Amount of fines paid or payable due to settle...,Total monetary value of paid and payable corru...,"$, €","[0, 1,000,000,000,000]"
38,NaN,NaN,Average number of hours of training on anti-c...,Average number of hours of training in anti-co...,Hours per Year,"[0,8760]"

In [29]:
unique_name=list(set(wr2['METRIC NAME']))

In [30]:
unique_name

['Male Employees Returned after Parental Leave (G4-LA3-c)',
 'Senior management hired from local community (G4-EC6-a)',
 'Product and service and labeling incidents of non-compliance - warning (G4-PR4-a2)',
 'Fair Trade Mechanism',
 'Percentage renewable fuel used',
 'Worker fatalities (G4-LA6-a)',
 'Percentage of employees that are temporary',
 'Environmental non-monetary sanctions (G4-EN29-a)',
 'Reduction in energy requirements of products and services (G4-EN7)',
 'energy is from renewable sources',
 'Waste Water Used (G4-EN8-a)',
 'Indirect legacy (G4-EO13-b)',
 'Employees Entitled to Parental Leave (G4-LA3-a)',
 'Customer data leaks, thefts, losses (G4-PR8-b)',
 'Marketing-related incidents of non-compliance - voluntary codes (G4-PR7-a3)',
 'Outside party complaints concerning breaches of customer privacy (G4-PR8-a1)',
 'Total Waste Generated (G4-EN23-a)',
 'Total water discharge (G4-EN22-a)',
 'Health and Safety incidents of non-compliance fined (G4-PR2-a1)',
 'MSA Performance Indicators',
 'Marketing-related incidents of non-compliance - warning (G4-PR7-a2)',
 'Renewable Energy (%)',
 'Total water withdrawals (G4-EN8-a)',
 'Combined Scope 1 and 2 Greenhouse Gas emissions',
 'Women in Unskilled Positions',
 'Volume of Significant Spills (G4-EN24-b)',
 'Fuel consumption from non-renewable sources (G4-EN3-a)',
 'Sulfur Oxide (SOx) emissions (G4-EN21-a)',
 'Indirect greenhouse gas (GHG) emissions (Scope 3) (G4-EN17-a)',
 'Alex H',
 'Non-Hazardous Waste Recycled (G4-EN23-a)',
 'Local suppliers spending (G4-EC9-a)',
 'Health and Safety incidents of non-compliance - voluntary codes (G4-PR2-a3)',
 'Employees Returned after Parental Leave (G4-LA3-c)',
 'Accessibility initiatives (G4-EO6-a)',
 'Energy intensity (G4-EN5-a)',
 'Hazardous Air Pollutant (HAP) emissions (G4-EN21-a)',
 'Hazardous Waste Created (G4-EN23-a)',
 'Male injury rate (G4-LA6-a)',
 'Incidents of discrimination per employee',
 'Direct greenhouse gas (GHG) emissions (Scope 1) (G4-EN15-a)',
 'Total Waste to Landfill (G4-EN23-a)',
 'Environmental fines (G4-EN29-a)',
 'Female Employees that Took Parental Leave (G4-LA3-b)',
 'Percentage hazardous waste recycled',
 'Occupational Risk (G4-LA7)',
 'Full-time employees (G4-10-b)',
 'Persistent Organic Pollutants (POP) (G4-EN21-a)',
 'Volatile Organic Compounds (VOC) emissions (G4-EN21-a)',
 'Injury rates (G4-LA6-a)',
 'Water Volume Recycled (G4-EN10-a)',
 'Health and Safety incidents of non-compliance - warning (G4-PR2-a2)',
 'Gender Entry Level Pay (G4-EC5)',
 'Collective bargaining (G4-11)',
 'Significant Spills (G4-EN24-a)',
 'Greenhouse Gas Emissions Scope 2',
 'Male worker fatalities (G4-LA6-a)',
 'Municipal water withdrawals (G4-EN8-a)',
 'Women in Management Positions',
 'Human rights impacts grievances filed (G4-HR12-a)',
 'Recycled Input Materials (G4-EN2-a)',
 'Complaints concerning breaches of customer privacy from regulatory bodies (G4-PR8-a2)',
 'Laureen van Breen',
 'NOx emissions (G4-EN21-a)',
 'Women in Skilled Positions',
 'Greenhouse Gas Emissions Scope 1',
 'Male Employees that Took Parental Leave (G4-LA3-b)',
 'Ground Water Withdrawals (G4-EN8-a)',
 'Indirect greenhouse gas (GHG) emissions (Scope 2) (G4-EN16-a)',
 'Environmental Protection Expenditures (G4-EN31-a)',
 'Product and service and labeling - Incidents of non-compliance to voluntary codes (G4-PR4-a3)',
 'Worker fatalities (% of workforce)',
 'Percentage non-hazardous waste recycled',
 'Percentage of waste recycled',
 'Energy Consumption Outside the Organization (G4-EN4)',
 'Access to Healthcare for Work-related Incidents',
 'Progress Scope 1 Emissions',
 'Female workers managers differential',
 'Female Employees Entitled to Parental Leave (G4-LA3-a)',
 'Temporary employees (G4-10-a)',
 'Fuel consumption from renewable sources (G4-EN3-b)',
 'Health and Safety representation (G4-LA5-b)',
 'MSA supply chain disclosure',
 'Rainwater collected directly and stored (G4-EN8-a)',
 'Water Recycled (%) (G4-EN10-b)',
 'Employees that Took Parental Leave (G4-LA3-b)',
 'MSA risk management (revised)',
 'Part-time employees (G4-10-b)',
 'Fines for products and services non-compliance (G4-PR9-a)',
 'MSA Business Performance Indicators',
 'Emissions of Ozone-Depleting Substances (ODS) (G4-EN20-a)',
 'Highest paid worker to median worker pay ratio (G4-54)',
 'Greenhouse gas (GHG) emissions intensity ratio (G4-EN18-a)',
 'Product and service and labeling incidents of non-compliance fined (G4-PR4-a1)',
 'Female injury rate (G4-LA6-a)',
 'Non-hazardous waste (G4-EN23-a)',
 'Incidents of discrimination (G4-HR3-a)',
 'Water Use',
 'Socially inclusive initiatives (G4-EO5-a)',
 'Female Employees Returned after Parental Leave (G4-LA3-c)',
 'Female worker fatalities (G4-LA6-a)',
 'Hazardous waste recycled (G4-EN23-a)',
 'Particulate Matter (PM) emissions (G4-EN21-a)',
 'Marketing-related incidents of non-compliance fined (G4-PR7-a1)',
 'Greenhouse Gas Emissions Scope 1 and 2 combined',
 'Male Employees Entitled to Parental Leave (G4-LA3-a)',
 'Total Waste Recycled (G4-EN23-a)']

In [31]:
%ls

 Volume in drive C is Windows
 Volume Serial Number is 0CF9-4541

 Directory of C:\Users\yzhhu\Desktop\stanley_svymky

2019/08/01  10:07    <DIR>          .
2019/08/01  10:07    <DIR>          ..
2019/07/31  17:29    <DIR>          .ipynb_checkpoints
2019/07/31  14:44    <DIR>          __pycache__
2019/07/30  16:11           134,020 crwdsurveymky_English_uie.ipynb
2019/07/12  15:37            34,994 crwdsurveymky_Spanish_uie.ipynb
2019/07/30  15:01            65,933 data prepare .ipynb
2019/08/01  09:53            62,429 dummy_data.ipynb
2019/07/30  10:25            14,717 GCI Units and Value Ranges - June03 - REVISED.xlsx
2019/08/01  10:06            12,228 IBM_International_Business_Machines_Corporation+Answer.csv
2019/07/30  16:08            15,769 process_functions.py
2019/07/12  15:37             2,733 README.md
2019/07/31  17:27            15,558 stanley_newmky.ipynb
2019/07/31  15:25               856 table.csv
2019/07/31  15:34               393 test3.py
2019/07/29  19:46    <DIR>          wr2
2019/07/11  13:50        26,239,411 wr2.csv
2019/07/12  15:37         2,813,812 wr2.zip
              13 File(s)     29,412,853 bytes
               5 Dir(s)  353,295,847,424 bytes free

In [81]:
dummy=pd.read_csv('IBM_International_Business_Machines_Corporation+Answer.csv')

In [82]:
dummy['METRIC NAME']=dummy['METRIC NAME'].apply(splitt)

In [83]:
dummy['COMPANY NAME']=dummy['COMPANY NAME'].apply(lambda x: x.split('(')[0])

In [84]:
dummy['ANSWER ID'].isna().sum()

17

In [85]:
dummy

,ANSWER ID,METRIC NAME,COMPANY NAME,YEAR,VALUE
0,2216332.0,Income Taxes Paid Net,IBM,2015,2657000000
1,2184968.0,Effective Income Tax Rate Continuing Operations,IBM,2015,0.16
2,2142260.0,Current Foreign Tax Expense Benefit,IBM,2015,2101000000
3,2084660.0,Effective Federal Income Tax Rate,IBM,2015,0.35
4,2115962.0,Deferred Income Tax Expense Benefit,IBM,2015,1387000000
5,2081430.0,Net Income,IBM,2015,13190000000
6,168534.0,CSR Report Available,IBM,2012,Yes
7,846237.0,CMR Smelters Identified,IBM,2014,264
8,171311.0,Scope 1 Emissions,IBM,2014,514464
9,166800.0,Meetings with NGO coalition regarding conflict...,IBM,2011,Yes
10,127183.0,EICC member,IBM,2015,TRUE
11,155406.0,EICC member,IBM,2015,TRUE
12,127177.0,BSR Member,IBM,2015,TRUE
13,890422.0,US effective Federal tax rate,IBM,2012,14.3
14,894989.0,Non-US effective tax rate,IBM,2012,24.57086807
15,167442.0,Publication of refiners,IBM,2011,0
16,168085.0,Verification of refiners or smelters through t...,IBM,2011,2
17,167656.0,Stated policy of auditing suppliers,IBM,2011,4
18,167978.0,Third-party audits of suppliers,IBM,2011,0
19,166684.0,Internal audits of suppliers' procurement prac...,IBM,2011,0
20,166907.0,Participation in CFS program,IBM,2011,2
21,166470.0,Financial support for audits,IBM,2011,1
22,167764.0,Stated policy of support for certification,IBM,2011,0
23,166363.0,Development of verifiably conflict-free products,IBM,2010,0
24,167228.0,Public statements in support of certification,IBM,2011,0
25,167014.0,Participation in OECD Due Diligence Guidance,IBM,2011,1
26,166256.0,Communication with NGO coalition regarding con...,IBM,2011,0
27,167871.0,Statement of advocacy for legislation in Europ...,IBM,2011,0
28,167549.0,Refiner visits,IBM,2011,1
29,127157.0,Newsweek Reputation Score,IBM,2014,3.7
...,...,...,...,...,...
76,NaN,Greenhouse Gas Emissions Scope 1,IBM,2014,514464
77,NaN,Greenhouse Gas Emissions Scope 2,IBM,2014,1978594
78,NaN,Greenhouse Gas Emissions Scope 1 and 2 combined,IBM,2014,2493058
79,NaN,Greenhouse Gas emissions per dollar profit,IBM,2014,5.37E-05
80,NaN,Greenhouse gas emissions per dollar revenue,IBM,2014,2.69E-05
81,NaN,Srivigneshwar R Prasad,IBM,2014,0
82,NaN,Richard Mills,IBM,2014,8.1
83,NaN,Richard Mills,IBM,2014,7
84,3753525.0,Employees,IBM,2016,380300
85,NaN,Employees,IBM,2016,380300
86,3883312.0,Undistributed Earnings of Foreign Subsidiaries,IBM,2016,71400000000
87,4252209.0,Net Income Attributable to Non Controlling Int...,IBM,2014,6000000
88,4526847.0,Conflict Minerals Report,IBM,2017,Yes
89,4573823.0,Controls,IBM,2013,1
90,4608010.0,Assets,IBM,2017,1.25356E+11
91,4656174.0,Good Will,IBM,2017,36788000000
92,4666652.0,Research and Development Expense,IBM,2017,5787000000
93,4679660.0,Net Income Attributable to the company,IBM,2017,5753000000
94,4694060.0,Revenue,IBM,2017,79139000000
95,NaN,Revenue,IBM,2017,79139000000
96,4703940.0,Gross Profit,IBM,2017,36227000000
97,NaN,Gross Profit,IBM,2017,36227000000
98,4822147.0,Unrecognized Tax Benefits that would impact Ef...,IBM,2017,6064000000
99,4875077.0,Income Loss From Continuing Operations Before ...,IBM,2017,10840000000
100,4880132.0,Cost of Goods Sold,IBM,2017,7256000000
101,NaN,Example WikiRating - CDP scores,IBM,2014,7.33
102,4968598.0,Comprehensive Income Net of Tax,IBM,2017,8559000000
103,NaN,Richard Mills,IBM,2015,10
104,NaN,Women on Board,IBM,2016,29
105,NaN,Mariana,IBM,2016,10

In [86]:
company=['apple','banana','stanley Inc','weeknd']

In [87]:
final=pd.DataFrame()
for i in company:
    dummy_a=dummy
    dummy_a['COMPANY NAME']=i
    final=pd.concat([final,dummy_a],axis=0)

In [91]:
dummy

,ANSWER ID,METRIC NAME,COMPANY NAME,YEAR,VALUE
0,2216332.0,Income Taxes Paid Net,weeknd,2015,2657000000
1,2184968.0,Effective Income Tax Rate Continuing Operations,weeknd,2015,0.16
2,2142260.0,Current Foreign Tax Expense Benefit,weeknd,2015,2101000000
3,2084660.0,Effective Federal Income Tax Rate,weeknd,2015,0.35
4,2115962.0,Deferred Income Tax Expense Benefit,weeknd,2015,1387000000
5,2081430.0,Net Income,weeknd,2015,13190000000
6,168534.0,CSR Report Available,weeknd,2012,Yes
7,846237.0,CMR Smelters Identified,weeknd,2014,264
8,171311.0,Scope 1 Emissions,weeknd,2014,514464
9,166800.0,Meetings with NGO coalition regarding conflict...,weeknd,2011,Yes
10,127183.0,EICC member,weeknd,2015,TRUE
11,155406.0,EICC member,weeknd,2015,TRUE
12,127177.0,BSR Member,weeknd,2015,TRUE
13,890422.0,US effective Federal tax rate,weeknd,2012,14.3
14,894989.0,Non-US effective tax rate,weeknd,2012,24.57086807
15,167442.0,Publication of refiners,weeknd,2011,0
16,168085.0,Verification of refiners or smelters through t...,weeknd,2011,2
17,167656.0,Stated policy of auditing suppliers,weeknd,2011,4
18,167978.0,Third-party audits of suppliers,weeknd,2011,0
19,166684.0,Internal audits of suppliers' procurement prac...,weeknd,2011,0
20,166907.0,Participation in CFS program,weeknd,2011,2
21,166470.0,Financial support for audits,weeknd,2011,1
22,167764.0,Stated policy of support for certification,weeknd,2011,0
23,166363.0,Development of verifiably conflict-free products,weeknd,2010,0
24,167228.0,Public statements in support of certification,weeknd,2011,0
25,167014.0,Participation in OECD Due Diligence Guidance,weeknd,2011,1
26,166256.0,Communication with NGO coalition regarding con...,weeknd,2011,0
27,167871.0,Statement of advocacy for legislation in Europ...,weeknd,2011,0
28,167549.0,Refiner visits,weeknd,2011,1
29,127157.0,Newsweek Reputation Score,weeknd,2014,3.7
...,...,...,...,...,...
76,NaN,Greenhouse Gas Emissions Scope 1,weeknd,2014,514464
77,NaN,Greenhouse Gas Emissions Scope 2,weeknd,2014,1978594
78,NaN,Greenhouse Gas Emissions Scope 1 and 2 combined,weeknd,2014,2493058
79,NaN,Greenhouse Gas emissions per dollar profit,weeknd,2014,5.37E-05
80,NaN,Greenhouse gas emissions per dollar revenue,weeknd,2014,2.69E-05
81,NaN,Srivigneshwar R Prasad,weeknd,2014,0
82,NaN,Richard Mills,weeknd,2014,8.1
83,NaN,Richard Mills,weeknd,2014,7
84,3753525.0,Employees,weeknd,2016,380300
85,NaN,Employees,weeknd,2016,380300
86,3883312.0,Undistributed Earnings of Foreign Subsidiaries,weeknd,2016,71400000000
87,4252209.0,Net Income Attributable to Non Controlling Int...,weeknd,2014,6000000
88,4526847.0,Conflict Minerals Report,weeknd,2017,Yes
89,4573823.0,Controls,weeknd,2013,1
90,4608010.0,Assets,weeknd,2017,1.25356E+11
91,4656174.0,Good Will,weeknd,2017,36788000000
92,4666652.0,Research and Development Expense,weeknd,2017,5787000000
93,4679660.0,Net Income Attributable to the company,weeknd,2017,5753000000
94,4694060.0,Revenue,weeknd,2017,79139000000
95,NaN,Revenue,weeknd,2017,79139000000
96,4703940.0,Gross Profit,weeknd,2017,36227000000
97,NaN,Gross Profit,weeknd,2017,36227000000
98,4822147.0,Unrecognized Tax Benefits that would impact Ef...,weeknd,2017,6064000000
99,4875077.0,Income Loss From Continuing Operations Before ...,weeknd,2017,10840000000
100,4880132.0,Cost of Goods Sold,weeknd,2017,7256000000
101,NaN,Example WikiRating - CDP scores,weeknd,2014,7.33
102,4968598.0,Comprehensive Income Net of Tax,weeknd,2017,8559000000
103,NaN,Richard Mills,weeknd,2015,10
104,NaN,Women on Board,weeknd,2016,29
105,NaN,Mariana,weeknd,2016,10

In [88]:
final

,ANSWER ID,METRIC NAME,COMPANY NAME,YEAR,VALUE
0,2216332.0,Income Taxes Paid Net,apple,2015,2657000000
1,2184968.0,Effective Income Tax Rate Continuing Operations,apple,2015,0.16
2,2142260.0,Current Foreign Tax Expense Benefit,apple,2015,2101000000
3,2084660.0,Effective Federal Income Tax Rate,apple,2015,0.35
4,2115962.0,Deferred Income Tax Expense Benefit,apple,2015,1387000000
5,2081430.0,Net Income,apple,2015,13190000000
6,168534.0,CSR Report Available,apple,2012,Yes
7,846237.0,CMR Smelters Identified,apple,2014,264
8,171311.0,Scope 1 Emissions,apple,2014,514464
9,166800.0,Meetings with NGO coalition regarding conflict...,apple,2011,Yes
10,127183.0,EICC member,apple,2015,TRUE
11,155406.0,EICC member,apple,2015,TRUE
12,127177.0,BSR Member,apple,2015,TRUE
13,890422.0,US effective Federal tax rate,apple,2012,14.3
14,894989.0,Non-US effective tax rate,apple,2012,24.57086807
15,167442.0,Publication of refiners,apple,2011,0
16,168085.0,Verification of refiners or smelters through t...,apple,2011,2
17,167656.0,Stated policy of auditing suppliers,apple,2011,4
18,167978.0,Third-party audits of suppliers,apple,2011,0
19,166684.0,Internal audits of suppliers' procurement prac...,apple,2011,0
20,166907.0,Participation in CFS program,apple,2011,2
21,166470.0,Financial support for audits,apple,2011,1
22,167764.0,Stated policy of support for certification,apple,2011,0
23,166363.0,Development of verifiably conflict-free products,apple,2010,0
24,167228.0,Public statements in support of certification,apple,2011,0
25,167014.0,Participation in OECD Due Diligence Guidance,apple,2011,1
26,166256.0,Communication with NGO coalition regarding con...,apple,2011,0
27,167871.0,Statement of advocacy for legislation in Europ...,apple,2011,0
28,167549.0,Refiner visits,apple,2011,1
29,127157.0,Newsweek Reputation Score,apple,2014,3.7
...,...,...,...,...,...
76,NaN,Greenhouse Gas Emissions Scope 1,weeknd,2014,514464
77,NaN,Greenhouse Gas Emissions Scope 2,weeknd,2014,1978594
78,NaN,Greenhouse Gas Emissions Scope 1 and 2 combined,weeknd,2014,2493058
79,NaN,Greenhouse Gas emissions per dollar profit,weeknd,2014,5.37E-05
80,NaN,Greenhouse gas emissions per dollar revenue,weeknd,2014,2.69E-05
81,NaN,Srivigneshwar R Prasad,weeknd,2014,0
82,NaN,Richard Mills,weeknd,2014,8.1
83,NaN,Richard Mills,weeknd,2014,7
84,3753525.0,Employees,weeknd,2016,380300
85,NaN,Employees,weeknd,2016,380300
86,3883312.0,Undistributed Earnings of Foreign Subsidiaries,weeknd,2016,71400000000
87,4252209.0,Net Income Attributable to Non Controlling Int...,weeknd,2014,6000000
88,4526847.0,Conflict Minerals Report,weeknd,2017,Yes
89,4573823.0,Controls,weeknd,2013,1
90,4608010.0,Assets,weeknd,2017,1.25356E+11
91,4656174.0,Good Will,weeknd,2017,36788000000
92,4666652.0,Research and Development Expense,weeknd,2017,5787000000
93,4679660.0,Net Income Attributable to the company,weeknd,2017,5753000000
94,4694060.0,Revenue,weeknd,2017,79139000000
95,NaN,Revenue,weeknd,2017,79139000000
96,4703940.0,Gross Profit,weeknd,2017,36227000000
97,NaN,Gross Profit,weeknd,2017,36227000000
98,4822147.0,Unrecognized Tax Benefits that would impact Ef...,weeknd,2017,6064000000
99,4875077.0,Income Loss From Continuing Operations Before ...,weeknd,2017,10840000000
100,4880132.0,Cost of Goods Sold,weeknd,2017,7256000000
101,NaN,Example WikiRating - CDP scores,weeknd,2014,7.33
102,4968598.0,Comprehensive Income Net of Tax,weeknd,2017,8559000000
103,NaN,Richard Mills,weeknd,2015,10
104,NaN,Women on Board,weeknd,2016,29
105,NaN,Mariana,weeknd,2016,10

In [101]:
'''
haha=True
lst=list()
a=0
while haha:
    if a not in lst:
        a= np.random.randint(len(final))
        lst.append(a)
    elif len(lst)>=30:
        haha=False
'''

KeyboardInterrupt:

In [103]:
lst=list()
b=np.random.randint(len(final))
for i in range(30):
    while b not in lst:
        lst.append(b)
        continue
    while b in lst:
        b=np.random.randint(len(final))
        continue
        
lst

[258,
 335,
 338,
 153,
 148,
 387,
 362,
 60,
 218,
 114,
 299,
 112,
 376,
 284,
 241,
 168,
 9,
 102,
 225,
 172,
 65,
 194,
 268,
 118,
 383,
 101,
 67,
 64,
 375,
 332]

In [105]:
final.index=range(len(final))

In [113]:
final.loc[lst,'VALUE']='Unknown'

In [115]:
final.iloc[lst]

,ANSWER ID,METRIC NAME,COMPANY NAME,YEAR,VALUE
258,846550.0,CMR Covers Copper,stanley Inc,2014,Unknown
335,167656.0,Stated policy of auditing suppliers,weeknd,2011,Unknown
338,166907.0,Participation in CFS program,weeknd,2011,Unknown
153,846556.0,CMR Covers Diamonds,banana,2014,Unknown
148,169427.0,Clean Energy Index,banana,2015,Unknown
387,2680507.0,Waste Productivity,weeknd,2016,Unknown
362,782455.0,Conflict Minerals Policy,weeknd,2016,Unknown
60,846477.0,Uses OECD Standard,apple,2014,Unknown
218,168534.0,CSR Report Available,stanley Inc,2012,Unknown
114,171311.0,Scope 1 Emissions,banana,2014,Unknown
299,4252209.0,Net Income Attributable to Non Controlling Int...,stanley Inc,2014,Unknown
112,168534.0,CSR Report Available,banana,2012,Unknown
376,846561.0,CMR Covers Cobalt,weeknd,2014,Unknown
284,2726085.0,ReportWatch Rating,stanley Inc,2015,Unknown
241,127157.0,Newsweek Reputation Score,stanley Inc,2014,Unknown
168,1355364.0,Newsweek Green Score,banana,2015,Unknown
9,166800.0,Meetings with NGO coalition regarding conflict...,apple,2011,Unknown
102,4968598.0,Comprehensive Income Net of Tax,apple,2017,Unknown
225,890422.0,US effective Federal tax rate,stanley Inc,2012,Unknown
172,2654228.0,Women on Board,banana,2016,Unknown
65,127165.0,Sustainability Board Committee,apple,2014,Unknown
194,4526847.0,Conflict Minerals Report,banana,2017,Unknown
268,846214.0,CMR DRC Conflict Status,stanley Inc,2014,Unknown
118,127177.0,BSR Member,banana,2015,Unknown
383,127165.0,Sustainability Board Committee,weeknd,2014,Unknown
101,NaN,Example WikiRating - CDP scores,apple,2014,Unknown
67,2662270.0,Scope 1 and 2 Intensity,apple,2013,Unknown
64,127161.0,Sustainability Pay Link,apple,2014,Unknown
375,846631.0,CMR Covers Coal,weeknd,2014,Unknown
332,894989.0,Non-US effective tax rate,weeknd,2012,Unknown

In [123]:
def rand_gen(num):
    lst1=list()
    b=np.random.randint(len(final))
    for i in range(num):
        while b not in lst1:
            lst1.append(b)
            continue
        while b in lst1:
            b=np.random.randint(len(final))
            continue
    return lst1

In [118]:
final.loc[lst1,'VALUE']=np.nan

In [136]:
final['RANGE']=0

In [138]:
final.loc[rand_gen(int(len(final)/2)),'RANGE']='[1,1000]'

In [140]:
for i in range(len(final)):
    if final.loc[i,'RANGE'] != '[1,1000]':
        final.loc[i,'RANGE'] = '[-100,100]'

In [142]:
final.loc[rand_gen(int(len(final)/10)),'RANGE']='Yes/NO'

In [144]:
for i in range(len(final)):
    if final.loc[i,'RANGE'] == 'Yes/NO':
        final.loc[i,'RANGE'] = 'Yes/No'

In [146]:
final.to_csv('dummy.csv')

In [152]:
final=pd.read_csv('dummy.csv',index_col=False)

In [153]:
final

,Unnamed: 0,ANSWER ID,METRIC NAME,COMPANY NAME,YEAR,VALUE,RANGE
0,0,2216332.0,Income Taxes Paid Net,apple,2015,2657000000,"[1,1000]"
1,1,2184968.0,Effective Income Tax Rate Continuing Operations,apple,2015,0.16,"[1,1000]"
2,2,2142260.0,Current Foreign Tax Expense Benefit,apple,2015,2101000000,"[-100,100]"
3,3,2084660.0,Effective Federal Income Tax Rate,apple,2015,0.35,"[1,1000]"
4,4,2115962.0,Deferred Income Tax Expense Benefit,apple,2015,1387000000,"[-100,100]"
5,5,2081430.0,Net Income,apple,2015,13190000000,"[-100,100]"
6,6,168534.0,CSR Report Available,apple,2012,Yes,Yes/No
7,7,846237.0,CMR Smelters Identified,apple,2014,264,Yes/No
8,8,171311.0,Scope 1 Emissions,apple,2014,514464,"[1,1000]"
9,9,166800.0,Meetings with NGO coalition regarding conflict...,apple,2011,Unknown,"[-100,100]"
10,10,127183.0,EICC member,apple,2015,TRUE,"[1,1000]"
11,11,155406.0,EICC member,apple,2015,TRUE,"[-100,100]"
12,12,127177.0,BSR Member,apple,2015,TRUE,"[-100,100]"
13,13,890422.0,US effective Federal tax rate,apple,2012,14.3,"[-100,100]"
14,14,894989.0,Non-US effective tax rate,apple,2012,24.57086807,"[-100,100]"
15,15,167442.0,Publication of refiners,apple,2011,0,"[1,1000]"
16,16,168085.0,Verification of refiners or smelters through t...,apple,2011,2,"[1,1000]"
17,17,167656.0,Stated policy of auditing suppliers,apple,2011,4,"[-100,100]"
18,18,167978.0,Third-party audits of suppliers,apple,2011,0,"[1,1000]"
19,19,166684.0,Internal audits of suppliers' procurement prac...,apple,2011,0,Yes/No
20,20,166907.0,Participation in CFS program,apple,2011,2,"[1,1000]"
21,21,166470.0,Financial support for audits,apple,2011,1,"[1,1000]"
22,22,167764.0,Stated policy of support for certification,apple,2011,0,"[-100,100]"
23,23,166363.0,Development of verifiably conflict-free products,apple,2010,0,"[-100,100]"
24,24,167228.0,Public statements in support of certification,apple,2011,0,Yes/No
25,25,167014.0,Participation in OECD Due Diligence Guidance,apple,2011,1,"[1,1000]"
26,26,166256.0,Communication with NGO coalition regarding con...,apple,2011,0,Yes/No
27,27,167871.0,Statement of advocacy for legislation in Europ...,apple,2011,0,"[-100,100]"
28,28,167549.0,Refiner visits,apple,2011,1,"[1,1000]"
29,29,127157.0,Newsweek Reputation Score,apple,2014,3.7,"[-100,100]"
...,...,...,...,...,...,...,...
394,394,NaN,Greenhouse Gas Emissions Scope 1,weeknd,2014,514464,"[1,1000]"
395,395,NaN,Greenhouse Gas Emissions Scope 2,weeknd,2014,1978594,"[-100,100]"
396,396,NaN,Greenhouse Gas Emissions Scope 1 and 2 combined,weeknd,2014,2493058,"[-100,100]"
397,397,NaN,Greenhouse Gas emissions per dollar profit,weeknd,2014,5.37E-05,"[-100,100]"
398,398,NaN,Greenhouse gas emissions per dollar revenue,weeknd,2014,2.69E-05,"[-100,100]"
399,399,NaN,Srivigneshwar R Prasad,weeknd,2014,0,"[-100,100]"
400,400,NaN,Richard Mills,weeknd,2014,8.1,"[-100,100]"
401,401,NaN,Richard Mills,weeknd,2014,7,"[1,1000]"
402,402,3753525.0,Employees,weeknd,2016,380300,"[1,1000]"
403,403,NaN,Employees,weeknd,2016,380300,"[1,1000]"
404,404,3883312.0,Undistributed Earnings of Foreign Subsidiaries,weeknd,2016,71400000000,"[1,1000]"
405,405,4252209.0,Net Income Attributable to Non Controlling Int...,weeknd,2014,6000000,"[1,1000]"
406,406,4526847.0,Conflict Minerals Report,weeknd,2017,Yes,"[1,1000]"
407,407,4573823.0,Controls,weeknd,2013,1,"[1,1000]"
408,408,4608010.0,Assets,weeknd,2017,1.25356E+11,"[-100,100]"
409,409,4656174.0,Good Will,weeknd,2017,36788000000,"[-100,100]"
410,410,4666652.0,Research and Development Expense,weeknd,2017,NaN,"[1,1000]"
411,411,4679660.0,Net Income Attributable to the company,weeknd,2017,5753000000,"[1,1000]"
412,412,4694060.0,Revenue,weeknd,2017,79139000000,"[-100,100]"
413,413,NaN,Revenue,weeknd,2017,79139000000,"[1,1000]"
414,414,4703940.0,Gross Profit,weeknd,2017,36227000000,Yes/No
415,415,NaN,Gross Profit,weeknd,2017,36227000000,"[1,1000]"
416,416,4822147.0,Unrecognized Tax Benefits that would impact Ef...,weeknd,2017,6064000000,"[1,1000]"
417,417,4875077.0,Income Loss From Continuing Operations Before ...,weeknd,2017,10840000000,"[-100,100]"
418,418,4880132.0,Cost of Goods Sold,weeknd,2017,7256000000,"[-100,100]"
419,419,NaN,Example WikiRating - CDP scores,weeknd,2014,7.33,"[1,1000]"
420,420,4968598.0,Comprehensive Income Net of Tax,weeknd,2017,8559000000,"[1,1000]"
421,421,NaN,Richard Mills,weeknd,2015,10,"[1,1000]"
422,422,NaN,Women on Board,weeknd,2016,29,Yes/No
423,423,NaN,Mariana,weeknd,2016,10,"[1,1000]"